#!/usr/bin/env python
""" This script prints the details of last 5 earthquake occured in Nepal in your terminal.
"""
from datetime import datetime
now=datetime.now()
print "Today's date: %s/%s/%s" %(now.month,now.day,now.year)

def get_page(url):
    try:
        import urllib
        return urllib.urlopen(url).read()
    except:
        return ''

data = get_page('https://docs.google.com/spreadsheets/u/0/d/1eeIOB58Dn5qRNWTySqrL35U8xY3JjZ7yhg5Dpxvbz8s/export' \
              '?format=csv&id=1eeIOB58Dn5qRNWTySqrL35U8xY3JjZ7yhg5Dpxvbz8s&gid=0')
print "Recent Earthquakes"
print data[111:-1]

