#!/usr/bin/env python
'''This script prints the details of last 5 earthquake occurred in Nepal
 in your terminal.
'''
from datetime import datetime
now = datetime.now()


def get_page(url):
    try:
        import urllib
        return urllib.urlopen(url).read()
    except:
        return ''

data = get_page('https://docs.google.com/spreadsheets/u/0/d/1eeIOB58Dn5qRNWTySqrL35U8xY3JjZ7yhg5Dpxvbz8s/export'
    '?format=csv&id=1eeIOB58Dn5qRNWTySqrL35U8xY3JjZ7yhg5Dpxvbz8s&gid=0')

if data:
	print "Today's date: %s/%s/%s" % (now.year, now.month, now.day)
	print "Recent Earthquakes:"
	print data[111:-1]
else:
	print "Check your internet connection."